[package]
name = "hocus-pocus"
version = "0.1.0"
authors = ["Without Boats <woboats@gmail.com>"]

[dependencies]
termios = "0.2.1"

[dependencies.notty-encoding]
git = "https://github.com/withoutboats/notty-encoding/"
